services:
  db:
    image: "postgres:16.0-alpine3.18"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5437:5432"

  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3100:3000"
    env_file:
      - .env # Load environment variables from .env
    depends_on:
      - db

volumes:
  db_data:
