default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("POSTGRES_POOL", 5) %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  database: <%= ENV["POSTGRES_DB"] %>

development:
  <<: *default
  database: <%= ENV["POSTGRES_DEVELOPMENT"] %>

test:
  <<: *default
  database: <%= ENV["POSTGRES_TEST"] %>

production:
  <<: *default
  database: <%= ENV["POSTGRES_PRODUCTION"] %>
