name: Database Setup

on:
  workflow_call:
    secrets:
      POSTGRES_STAGE:
        required: true

jobs:
  database:
    runs-on: ubuntu-latest
    steps:
      - name: Setup database
        run: bundle exec rails db:create db:schema:load
        env:
          DATABASE_URL: ${{ secrets.POSTGRES_STAGE }}
          RAILS_ENV: test
