name: CI
on: [pull_request]

jobs:
  setup:
    name: Setup Env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.4"
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

  database:
    name: Setup Database
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Setup database
        run: bundle exec rails db:create db:schema:load
        env:
          DATABASE_URL: ${{ secrets.POSTGRES_STAGE }}
          RAILS_ENV: test

  tests:
    name: RSpec Tests
    needs: database
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: bundle exec rspec
        env:
          DATABASE_URL: ${{ secrets.POSTGRES_STAGE }}
          RAILS_ENV: test
