name: CI

on: [pull_request]

jobs:
  setup:
    uses: ./.github/workflows/jobs/setup.yml
    secrets:
      POSTGRES_STAGE: ${{ secrets.POSTGRES_STAGE }}

  database:
    needs: setup
    uses: ./.github/workflows/jobs/database.yml
    secrets:
      POSTGRES_STAGE: ${{ secrets.POSTGRES_STAGE }}

  tests:
    needs: database
    uses: ./.github/workflows/jobs/rspec.yml
    secrets:
      POSTGRES_STAGE: ${{ secrets.POSTGRES_STAGE }}
