name: RSpec Tests

on:
  workflow_call:
    secrets:
      POSTGRES_STAGE:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: bundle exec rspec
        env:
          DATABASE_URL: ${{ secrets.POSTGRES_STAGE }}
          RAILS_ENV: test
